wandb_version: 1

gamma:
  desc: null
  value: 0.99
lr:
  desc: null
  value: 0.00025
batch_size:
  desc: null
  value: 64
eps:
  desc: null
  value: 1.0
eps_decay:
  desc: null
  value: 0.995
eps_min:
  desc: null
  value: 0.025
memory_size:
  desc: null
  value: 10000
max_steps:
  desc: null
  value: 1000
max_episodes:
  desc: null
  value: 10000
env_name:
  desc: null
  value: CartPole-v1
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683063988.413503
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.10
      5: 0.15.0
      8:
      - 5
